### ISSUE TITLE
The HTML Content Template (<template>) element should have a permitted parent: <body>, <frameset>, <head>, <dl> and <colgroup> 

### ISSUE THREAD

**Issue by rjanse** [bengfarrell/webcomponentsinaction#1]
Hi!

I read this:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

So, should the HTML Content Template `<template>` element have a permitted parent: `<body>`, `<frameset>`, `<head>`, `<dl>` or `<colgroup>`?

https://github.com/bengfarrell/webcomponentsinaction/blob/0e809a77b9552f3aa79959ee9270c05a1e3f359f/chapter7/7.3-businesscardtemplates/index.html#L8

**Comment by bengfarrell** [comment]
Hi! Thanks for the issue! This is a tricky one! The MDN documentation is the only place I'm seeing the permitted parents, and I just looked over the element specification as well. I just opened up an account on MDN to inquire about this.

Overall, however, it works in practice, and I might guess that either browsers have improved to the point where this isn't an issue anymore or they wanted to highlight specifics instances where it did not work - like the `<dl>` and `<colgroup>` with a span attribute and simply just included everything else accidentally not including `<html>`. Or "with a span attribute" applies to every exclusion they are calling out, and the important takeaway is "Don't use template with a parent that has a span attribute".

In my example, specifically - it is a bit non standard to just slap the template tag in the `<html>` and not placing it in the `<head>`. So that might be a good thing for me to edit - but I do want to see how it matters, because if I get confirmation that it doesn't matter, I don't think I will change it.

Either way thanks!

**Comment by bengfarrell** [comment]
I'm going to keep this issue open while I keep track of the latest, but again thanks! I got in touch with someone from MDN who thinks the docs are wrong (says the template entry is quite old at this point). He's opened up a ticket here: https://github.com/mdn/sprints/issues/1382

**Comment by bengfarrell** [comment]
Long time, but I can finally close this. I got a notification just now that the MDN docs have been corrected and its thanks to you for raising this issue! Thanks again, you rock!
